### ISSUE TITLE
Turn this tutorial into a website?

### ISSUE THREAD

**Issue by FDelporte** [dykstrom/mazela-man#1]
Hello @dykstrom, you really did an amazing job here! Would you consider turning this into a free hosted website with GitHub Actions and Pages? By using https://gohugo.io/ this can be done very easy and it is also still readable as readme-files here in the repository.

You can check a similar approach on https://pi4j.com/ and https://github.com/Pi4J/pi4j.github.io/tree/main/content

I can give you a hand to make the transition to a site.

**Comment by dykstrom** [comment]
Yeah, if it is not too much work setting up and maintaining the stuff, I think it would be cool. It would probably make the tutorial more accessible to some people that way. But I still want it to be usable the way I planned from the beginning, so I don't want the original repo to be cluttered with a lot of website stuff.

Also, I would appreciate some help with this (as you write) since it is not anything I've done before.

**Comment by FDelporte** [comment]
First experiments on https://fdelporte.github.io/mazela-man/manual/ 

Sources: https://github.com/FDelporte/mazela-man (main branch with the sources in "static" directory")

Website: https://github.com/FDelporte/mazela-man/tree/gh-pages

Created with Action: https://github.com/FDelporte/mazela-man/actions

**Comment by dykstrom** [comment]
Looks promising! I like the look of the site. I can see the main structure is in place, but there are no images yet. Thanks for taking the time to do this!

**Comment by FDelporte** [comment]
indeed, images is part of the "second" experiment round (soon) ;-)

**Comment by FDelporte** [comment]
broken links and images OK now
https://fdelporte.github.io/mazela-man/manual/

depending on wether the site is published with a github domainname or dedicated one, a full find/replace will need to be done to fillin the correct final link.

if OK I will do PR to this original repository

**Comment by dykstrom** [comment]
Very nice! It certainly looks much better this way than just reading the README files. Your solution with the back and forward buttons are much better than what I put into the README files. I have a couple of questions and comments. Some of them probably come from me not understanding how this stuff works and what the final result will be like.

* All the sources and maven modules are now in a folder called static. This means the repo cannot be used as a normal maven project. If I clone your forked repo and open the pom file it cannot find its submodules and build. The intent of the tutorial was that you clone the repo, change and build the code and run the game in different stages. With the new setup this is not possible. Or am I missing something here? In your original example, Pi4j, there was a separate repo for the site, called pi4j.github.io, like the URL of the site. When I read about GitHub pages I saw that was a common way to do thing, so I kind of assumed that would be our end result as well. Would it be possible to setup a new repo mazela-man.github.io that is updated with github actions, so that the original repo remains usable as a maven project?
* What needs to happen in the future if I change something in the tutorial, say fix a bug, or add a new chapter? Will the site be rebuilt automatically with github actions, or will I have to do it manually?

And some more detailed comments...

* I would prefer to have the Introduction on the same level as the other chapters. If we need two levels, the top README could be the top level.
* The home button is broken. I guess it should lead to the top README?
* A number of links that are supposed to point to the resources folder on the top level are broken. This may be because the structure is not completely finished, but I don't know. The ones I have found are:
  * on the start page, named "here"
  * in chapter 4, named "here"
  * in chapter 5, named "resources"
  * in chapter 6, named "resources"
  * in chapter 8, named "resources"
* the link named "next chapter" in chapter 7 is actually meant to take you to the "levels" folder of the next chapter, not to the main page of the chapter. A little tricky this one, since all other links named "next chapter" take you to a chapter...
* if you click on a link to chapter 9, you end up in the middle of chapter 9, not at the top
* I did not plan to get a special domain name for the tutorial. My guess was that the URL would be dykstrom.github.io/mazela-man.

I hope that you are not put off by all my comments. I really appreciate what you do! The tutorial looks much better in your version, but I would still like it to be usable as I planned from the beginning. :-)

**Comment by AlmasB** [comment]
Perhaps, having a repository purely for code and another repository purely for the website / tutorial is the way forward? Then managing both code and website separately becomes a much simpler task.

**Comment by FDelporte** [comment]
@AlmasB yes indeed, I was thinking in the same direction.
@dykstrom maybe the fastest way forward: can you create a new repository for the site and give me access to it? then I will move the site-specific content to that one and set it up for you

**Comment by dykstrom** [comment]
Yes, should it then be named "mazela-man.github.io", is that the standard?

**Comment by FDelporte** [comment]
yep that's ok

**Comment by dykstrom** [comment]
@FDelporte I have invited you as a collaborator. Do I need to assign any special permissions to you, or is that enough?

**Comment by FDelporte** [comment]
@dykstrom can you make me admin of that project so I can also work on the settings?

**Comment by dykstrom** [comment]
Where do I do that? I cannot find anything under Manage access.

**Comment by FDelporte** [comment]
<img width="1287" alt="Screenshot 2021-03-30 at 15 04 48" src="https://user-images.githubusercontent.com/1415873/112993484-8d1cca80-9169-11eb-8c14-aed573fa322c.png">

**Comment by dykstrom** [comment]
Mine looks like this. No role...

![image](https://user-images.githubusercontent.com/650850/113000172-dc65f980-916f-11eb-99c1-9026fbb2da63.png)

**Comment by FDelporte** [comment]
pitty. then you will need need to do the pages configuration ;-)

**Comment by AlmasB** [comment]
Frank, perhaps you can just transfer ownership of the repo you already
created?

**Comment by FDelporte** [comment]
need to clean up anyhow as we want to remove the code from the website project so won't be a problem

**Comment by FDelporte** [comment]
All handled and site online on https://dykstrom.github.io/mazela-man-web/home/

Regarding your questions:
* as the site is now isolated, you can remove the extended readmes from the source file project and refer to the site
* if a content change is needed, checkout master of the site repository, make the change, commit to master and wait a few minutes "for the magic to happen", and a new version of the site will be available thanks to GitHub Actions and Pages
* all pages on the same level now and listed in the menu
* home button is removed and added in menu
* all links should be fixed
* no dedicated domain name needed, GitHub provides you one in dykstrom.github.io

**Comment by AlmasB** [comment]
This stuff looks fantastic, many thanks @FDelporte

**Comment by FDelporte** [comment]
> This stuff looks fantastic, many thanks @FDelporte

With pleasure and thanks to the original big work of @dykstrom

**Comment by dykstrom** [comment]
Yes, it looks really great! Thank you! I'll look over the links once more, and try to update them myself. :-)

Just to make sure I understand. There _is_ a link between the site repo and the site, so whenever I update the site repo, it will be automatically published to the site. But there is not any link between the original repo and the site repo. So if I update the original repo, I will have to update the site repo manually?

And you suggest I remove the README files from the original repo and just refer to the site instead?

@AlmasB I guess it is better to link to the site instead from the FXGL page?

**Comment by FDelporte** [comment]
correct

site repo -> push -> github action starts to build GoHugo site -> publishes to GitHub pages

original repo -> not linked to site repo --> so indeed I think it makes sense to remove the documentation pages from this on so you don't need to maintain them in two repos

**Comment by dykstrom** [comment]
One more question, about the branches. It says that "the site is published on each commit into the "gh-pages" branch of this repository". Does that mean that the "master" branch is not used for anything?

**Comment by AlmasB** [comment]
> @AlmasB I guess it is better to link to the site instead from the FXGL page?

Let me know once you are happy with the site and I'll update the link

**Comment by FDelporte** [comment]
the master branch is the one you need to work in, so meaning:

- master 
   - the gohugo settings, theme and md-files 
   - the GitHub Action file in (.github/workflows)
   - any content change you want to do, needs to be done here
   - so this is your "working directory"
- gh-pages 
   - html website created by GitHub Action 
   - used to publish with GitHub pages
   - so automatically created/updated, you should never touch anything here

**Comment by dykstrom** [comment]
@AlmasB Now I have fixed some more links, and tweaked the text a little, so now I'm happy with the web version of the tutorial.
@FDelporte Thanks for your great work! I now consider this issue done.
